export const menuItems = [
    {
        title: "Dashboard",
        fieldKey: "dashboard",
        alternateFieldKey: "dashboardMaster",
        imageUrl: "/assets/navbar-menu/Dashboard.svg",
        redirectUrl: "/",
        permissionCode: "DASHBOARD",
    },
    {
        title: "School",
        fieldKey: "school",
        imageUrl: "/assets/navbar-menu/Dashboard.svg",
        permissionCode: "SCHOOL_MANAGEMENT",
        child: [
            {
                title: "School List",
                fieldKey: "skul",
                redirectUrl: "/school",
                permissionCode: "SCHOOL_MANAGEMENT",
                // addPath: "/product-master/add-product",
                // imgURL: "/assets/dashboard-icons/product_master.svg",
                // addImgURL: "/assets/dashboard-icons/add/product_master.svg",
            },
        ],
    },
    {
        title: "Sessions ",
        fieldKey: "Sessions",
        imageUrl: "/assets/navbar-menu/Dashboard.svg",
        permissionCode: "SESSION",
        child: [
            {
                title: "Session List",
                fieldKey: "session",
                redirectUrl: "/session",
                permissionCode: "SESSION_MANAGEMENT",
                // addPath: "/product-master/add-product",
                // imgURL: "/assets/dashboard-icons/product_master.svg",
                // addImgURL: "/assets/dashboard-icons/add/product_master.svg",
            },
        ],
    },
    {
        title: "Teacher",
        fieldKey: "teacher",
        imageUrl: "/assets/navbar-menu/Dashboard.svg",
        permissionCode: "TEACHER",
        child: [
            {
                title: "Registration",
                fieldKey: "techr_regi",
                redirectUrl: "/teacherRegistration",
                permissionCode: "ADD_TEACHER",
                // addPath: "/product-master/add-product",
                // imgURL: "/assets/dashboard-icons/product_master.svg",
                // addImgURL: "/assets/dashboard-icons/add/product_master.svg",
            },
            {
                title: "Teacher List",
                fieldKey: "techr_List",
                redirectUrl: "/teacher",
                permissionCode: "LIST_TEACHER",
                // addPath: "/product-master/add-product",
                // imgURL: "/assets/dashboard-icons/product_master.svg",
                // addImgURL: "/assets/dashboard-icons/add/product_master.svg",
            },
        ],
    },
    {
        title: "Classes & Section",
        fieldKey: "cas",
        imageUrl: "/assets/navbar-menu/Dashboard.svg",
        permissionCode: "CLASS",
        child: [
            {
                title: "Classes & section List",
                fieldKey: "classes",
                redirectUrl: "/classes",
                permissionCode: "LIST_CLASS",
                // addPath: "/product-master/add-product",
                // imgURL: "/assets/dashboard-icons/product_master.svg",
                // addImgURL: "/assets/dashboard-icons/add/product_master.svg",
            },
            // {
            //   title: "Class Fee",
            //   fieldKey: "cls_fee",
            //   redirectUrl: "/classes_fee",
            //   // addPath: "/product-master/add-product",
            //   // imgURL: "/assets/dashboard-icons/product_master.svg",
            //   // addImgURL: "/assets/dashboard-icons/add/product_master.svg",
            // },
        ],
    },
    {
        title: "Student",
        fieldKey: "student",
        imageUrl: "/assets/navbar-menu/Dashboard.svg",
        permissionCode: "STUDENT",
        child: [
            {
                title: "Resigtration",
                fieldKey: "stud_regi",
                imgURL: "/assets/navbar-menu/Dashboard.svg",
                redirectUrl: "/student_registration_form",
                permissionCode: "ADD_STUDENT",
            },
            {
                title: "Student List",
                fieldKey: "stu_list",
                imgURL: "/assets/navbar-menu/Dashboard.svg",
                redirectUrl: "/student",
                permissionCode: "LIST_STUDENT",
            },
        ],
    },
    {
      title: "Receipt",
      fieldKey: "receipt",
      imageUrl: "/assets/navbar-menu/Dashboard.svg",
      permissionCode: "RECEIPT",
      child: [
        {
          title: "Add Fee",
          fieldKey: "fee",
          redirectUrl: "/receipt",
          permissionCode: "LIST_RECEIPT",
        },
      ],
    },
    {
      title: "Users",
      fieldKey: "users",
      imageUrl: "/assets/navbar-menu/Dashboard.svg",
      permissionCode: "USERS",
      child: [
          {
              title: "Manage Users",
              fieldKey: "manage_users",
              redirectUrl: "/users",
              permissionCode: "USER_MANAGEMENT",
          },
      ],
    },
    {
        title: "Reports",
        fieldKey: "reports",
        imageUrl: "/assets/navbar-menu/Dashboard.svg",
        permissionCode: "REPORTS",
        child: [
          {
            title: "Pending Fee",
            fieldKey: "pending-fee",
            redirectUrl: "/reports/pending-fee",
            permissionCode: "PENDING_FEE_REPORT",
          },
        ],
      },
];
